# Lint markdown files

name: Lint

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdown-lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: '**/*.md'

  update-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install deps
        run: npm install -g markdown-toc
      - name: Update TOC
        run: cd $GITHUB_WORKSPACE/docs && ./update-toc.sh
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add TOC changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
